#!/bin/bash
#SBATCH -J CC_imputation_check
#SBATCH -N 1 # number of nodes
#SBATCH -n 1 # number of cores
#SBATCH --mem=8G # memory pool for all cores
#SBATCH -t 0-25:00 # time (D-HH:MM)
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.err # STDERR
#SBATCH --mail-user=anna.tyler@jax.org
#SBATCH --mail-type=END
# example use: sbatch --export=tissue_name="adipose",capeType="query",delete_previous="FALSE" CC-RIX_expression_effects


cd $SLURM_SUBMIT_DIR

module load singularity

singularity exec /projects/carter-lab/atyler/Containers/som.sif R -e 'rmarkdown::render(here::here("Documents", "1.Setup_Data", "CC-RIX_expression_effects.Rmd"))' --args "$tissue_name" "$capeType" "$delete_previous"
