#!/bin/bash
#SBATCH -J high_dimensional_mediation
#SBATCH -N 1 # number of nodes
#SBATCH -n 1 # number of cores
#SBATCH --mem=8G # memory pool for all cores
#SBATCH -t 0-4:00 # time (D-HH:MM)
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.err # STDERR
#SBATCH --mail-user=anna.tyler@jax.org
#SBATCH --mail-type=END
#for now set arguments in Rmd file
# example use: sbatch high_dimensional_mediation

cd $SLURM_SUBMIT_DIR

module load singularity

singularity exec ../../../Containers/CCA_transcripts.sif R -e 'rmarkdown::render(here::here("Documents", "1.Setup_Data", "High_Dimensional_Mediation.Rmd"))'
