#!/bin/bash
#SBATCH -J prioritize_trans
#SBATCH -N 1 # number of nodes
#SBATCH -n 20 # number of cores
#SBATCH --mem=8G # memory pool for all cores
#SBATCH -t 0-1:30 # time (D-HH:MM)
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.err # STDERR
#SBATCH --mail-user=anna.tyler@jax.org
#SBATCH --mail-type=END
# example use: sbatch --export=tissue_name="Adipose",n_cores="20" prioritize_trans

cd $SLURM_SUBMIT_DIR

module load singularity

singularity exec ../../../Containers/CCA_transcripts.sif R -e 'rmarkdown::render(here::here("Documents", "1.Setup_Data", "3.1_Prioritization_with_trans.Rmd"))' --args "$tissue_name" "$n_cores"
