#!/bin/bash
#SBATCH -J create_container
#SBATCH -N 1 # number of nodes
#SBATCH -n 1 # number of cores
#SBATCH --mem=8G # memory pool for all cores
#SBATCH -t 0-24:00 # time (D-HH:MM)
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.err # STDERR
#SBATCH --mail-user=anna.tyler@jax.org
#SBATCH --mail-type=END
# example use: sbatch singularity_create

cd $SLURM_SUBMIT_DIR

module load singularity
builder="singularity run http://s3-far.jax.org/builder/builder"
$builder Singularity.def R.sif


