#!/bin/bash
#SBATCH -J CC-RIX_SOM
#SBATCH -N 1 # number of nodes
#SBATCH -n 1 # number of cores
#SBATCH --mem=8G # memory pool for all cores
#SBATCH -t 0-25:00 # time (D-HH:MM)
#SBATCH -o slurm.%N.%j.out # STDOUT
#SBATCH -e slurm.%N.%j.err # STDERR
#SBATCH --mail-user=anna.tyler@jax.org
#SBATCH --mail-type=END
# example use: sbatch --export=tissue_name="adipose",contrast="Diet",delete_previous="FALSE" SOM_CC-RIX_contrast

cd $SLURM_SUBMIT_DIR

module load singularity

singularity exec /projects/carter-lab/atyler/Containers/som.sif R -e 'rmarkdown::render(here::here("Documents", "1.Setup_Data", "SOM_CC-RIX_One_Contrast.Rmd"))' --args "$tissue_name" "$contrast" "$delete_previous"
